AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: 'aws-cdk=1.0.0,@aws-cdk/core=1.0.0,@aws-cdk/cx-api=1.0.0,jsii-runtime=node.js/v8.12.0'